name: Build GitHub Pages from RSS

on:
  schedule:
    # Her gün 09:00 İstanbul (UTC+3) civarı
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install feedparser

      - name: Generate static news page
        env:
          RSS_URL: "https://gundemsivas.com/rss.xml"  # ← RSS adresinizi buraya yazın
          MAX_ITEMS: "30"
        run: python scripts/rss_to_pages.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

